# Generated by Django 5.1.15 on 2026-09-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(max_length=1000, unique=True, verbose_name='URL')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='Bolsa')),
                ('search_term', models.CharField(blank=True, max_length=200, verbose_name='Búsqueda')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('company', models.CharField(blank=True, max_length=300, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('is_remote', models.BooleanField(blank=True, null=True, verbose_name='Remoto')),
                ('job_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('date_posted', models.DateField(blank=True, null=True, verbose_name='Publicada')),
                ('min_amount', models.FloatField(blank=True, null=True, verbose_name='Salario mín.')),
                ('max_amount', models.FloatField(blank=True, null=True, verbose_name='Salario máx.')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Moneda')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('match_score', models.IntegerField(db_index=True, default=0, verbose_name='Match')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Guardada')),
            ],
            options={
                'ordering': ['-match_score', '-date_posted', '-created_at'],
                'indexes': [models.Index(fields=['site'], name='jobs_job_site_96c4f5_idx'), models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx')],
            },
        ),
    ]
