# Generated by Django 5.1.15 on 2026-09-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de postulación'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_industry',
            field=models.CharField(blank=True, max_length=200, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_num_employees',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Web empresa'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorita'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url_direct',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL directa'),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'Sin postular'), ('applied', 'Postulada'), ('interview', 'Entrevista'), ('offer', 'Oferta'), ('rejected', 'Rechazada'), ('discarded', 'Descartada')], db_index=True, default='new', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
    ]
