# Generated by Django 5.1.15 on 2026-09-10 04:08

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_applied_at_job_company_industry_job_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('file', models.FileField(upload_to=jobs.models.cv_upload_path, verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Palabras clave')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
