# Generated by Django 5.1.15 on 2026-09-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'ordering': ['email'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='cv',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='jobs.owner'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.owner'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['owner'], name='jobs_job_owner_i_90573d_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('owner', 'job_url'), name='uniq_owner_job_url'),
        ),
    ]
