# Generated by Django 5.1.15 on 2026-09-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_owner_alter_job_job_url_cv_owner_job_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='text',
            field=models.TextField(blank=True, verbose_name='Texto extraído'),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Vector'),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modelo del vector'),
        ),
    ]
