# Generated by Django 5.1.15 on 2026-09-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='owner',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Género'),
        ),
    ]
